// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCarWebApi.Data;

#nullable disable

namespace SimpleCarWebApi.Migrations
{
    [DbContext(typeof(CarDbContext))]
    partial class CarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleCarWebApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarBodyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("TopSpeed")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarBodyTypeId");

                    b.HasIndex("CarBrandId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarBodyTypeId = 1,
                            CarBrandId = 1,
                            Description = "Audi Q3 1.4 TFSI is a 2011 SUV model with 6 speed manual transmission.\r\n                        With a power of 110 KW you can reach 0-100km h in just 9,2 seconds and a maximum speed of 203 km/h with an urban consumption of 7,4 l/100km.\r\n                        The engine has a capacity of 1395 cc with 4, in line cylinders and 4 valves per cylinders.\r\n                        Also this model has a weight of with coil springs front suspension and a coil springs rear suspension.",
                            Model = "Audi Q3 1.4 TFSI",
                            Price = 36.430m,
                            TopSpeed = 203.0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            CarBodyTypeId = 2,
                            CarBrandId = 2,
                            Description = "Alfa Romeo 156 1.6 T.Spark 16V Progression is a 2002 Sedan model with 5 speed manual transmission.\r\n                        With a power of 88 KW you can reach 0-100km h in just 10,5 seconds and a maximum speed of 200 km/h with an urban consumption of 11,4 l/100km.\r\n                        The engine has a capacity of 1598 cc with 4, in line cylinders and 4 valves per cylinders.\r\n                        Also this model has a weight of with coil springs front suspension and a coil springs rear suspension.",
                            Model = "Alfa Romeo 156 1.6 T.Spark 16V Progression",
                            Price = 24.685m,
                            TopSpeed = 200.0,
                            Year = 2002
                        },
                        new
                        {
                            Id = 3,
                            CarBodyTypeId = 2,
                            CarBrandId = 3,
                            Description = "Dodge Avenger 2.0 SE is a 2007 Sedan model with 5 speed manual transmission.\r\n                        With a power of 115 KW you can reach 0-100km h in just 10,8 seconds and a maximum speed of 200 km/h with an urban consumption of 10,7 l/100km.\r\n                        The engine has a capacity of 1998 cc with 4, in line cylinders and 4 valves per cylinders.\r\n                        Also this model has a weight of with coil springs front suspension and a coil springs rear suspension.",
                            Model = "Dodge Avenger 2.0 SE",
                            Price = 24.450m,
                            TopSpeed = 204.0,
                            Year = 2007
                        },
                        new
                        {
                            Id = 4,
                            CarBodyTypeId = 3,
                            CarBrandId = 4,
                            Description = "BMW 840i Cabrio is a 2019 Convertible model with 8 speed automatic.\r\n                        With a power of 250 KW you can reach 0-100km h in just 5,3 seconds and a maximum speed of 250 km/h with an urban consumption of 9,1 l/100km.\r\n                        The engine has a capacity of 2998 cc with 6, in line cylinders and 4 valves per cylinders.\r\n                        Also this model has a weight of with coil springs front suspension and a coil springs rear suspension.",
                            Model = "BMW 840i Cabrio",
                            Price = 120.141m,
                            TopSpeed = 250.0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            CarBodyTypeId = 4,
                            CarBrandId = 5,
                            Description = "Hyundai Coupe 2.0i FX DynamicVersion is a 2004 Coupe model with 5 speed manual transmission.\r\n                        With a power of 105 KW you can reach 0-100km h in just 9,1 seconds and a maximum speed of 208 km/h with an urban consumption of 10,9 l/100km.\r\n                        The engine has a capacity of 1975 cc with 4, in line cylinders and 4 valves per cylinders.\r\n                        Also this model has a weight of with coil springs front suspension and a coil springs rear suspension.",
                            Model = "Hyundai Coupe 2.0i FX DynamicVersion",
                            Price = 26.195m,
                            TopSpeed = 208.0,
                            Year = 2004
                        },
                        new
                        {
                            Id = 6,
                            CarBodyTypeId = 1,
                            CarBrandId = 6,
                            Description = "Nissan Juke 1.6 Juke is a 2010 SUV model with 5 speed manual transmission.\r\n                        With a power of 68 KW you can reach 0-100km h in just 12,0 seconds and a maximum speed of 168 km/h with an urban consumption of 7,6 l/100km.\r\n                        The engine has a capacity of 1598 cc with 4, in line cylinders and 4 valves per cylinders.\r\n                        Also this model has a weight of with coil springs front suspension and a coil springs rear suspension.",
                            Model = "Nissan Juke 1.6 Juke",
                            Price = 19.490m,
                            TopSpeed = 168.0,
                            Year = 2010
                        });
                });

            modelBuilder.Entity("SimpleCarWebApi.Models.CarBodyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarBodyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Convertible"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Coupe"
                        });
                });

            modelBuilder.Entity("SimpleCarWebApi.Models.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dodge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("SimpleCarWebApi.Models.Car", b =>
                {
                    b.HasOne("SimpleCarWebApi.Models.CarBodyType", "CarBodyType")
                        .WithMany("Cars")
                        .HasForeignKey("CarBodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleCarWebApi.Models.CarBrand", "CarBrand")
                        .WithMany("Cars")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBodyType");

                    b.Navigation("CarBrand");
                });

            modelBuilder.Entity("SimpleCarWebApi.Models.CarBodyType", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("SimpleCarWebApi.Models.CarBrand", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
